project:
  name: employee-safira
  description: employee-safira
  import-type: openapi_spec
  java:
    management: maven
    springbootVersion: null
    package: br.com.vertigo.employee
    version: null
  language: java
  framework: quarkus
  applicationPort: "8080"
  kubernetes:
    namespace: null
  docker:
    registry: null
  export-openapi-kubernetes: false
